# Generated by Django 2.2.2 on 2019-07-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_os_version', models.CharField(blank=True, choices=[('-', 'Pick One'), ('r', 'RHEL'), ('o', 'OpenSuse'), ('c', 'CentOS')], default='-', help_text='Current OS Version', max_length=1)),
                ('current_rad_version', models.CharField(default='2.9.1b', help_text='Current Radimetrics Version ', max_length=10)),
                ('type_of_server', models.CharField(choices=[('-', 'Pick One'), ('p', 'PROD'), ('t', 'TEST'), ('c', 'CONTRAST ONLY'), ('p', 'PRE-PROCESSOR'), ('e', 'ENTERPRISE')], default='-', help_text='Type of Server', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CaseNumberModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdi_count', models.IntegerField(default=0)),
                ('upgrade_total_time', models.IntegerField(default=0)),
                ('upa', models.BooleanField()),
                ('contact_cust', models.BooleanField()),
                ('min_server_req', models.BooleanField()),
                ('upgrade_complete', models.BooleanField()),
                ('dosecalc_suppression', models.BooleanField()),
                ('ip_page_updated', models.BooleanField()),
                ('wo_type', models.CharField(blank=True, choices=[('-', 'Pick One'), ('s', 'VSS'), ('u', 'VCU')], default='-', help_text='Work Order Type', max_length=1)),
                ('minimum_rad_version', models.CharField(default='2.9.1b', help_text='Color Coded Red for current_rad_version<2.7a, Yellow for current_rad_version<2.9b and Green for current_rad_version == minimum_rad_version', max_length=10)),
                ('sched_upgrade_date', models.DateTimeField(blank=True, null=True)),
                ('upgrade_date', models.DateTimeField(blank=True, null=True)),
                ('primary_email', models.CharField(blank=True, help_text='Primary Email', max_length=100)),
                ('clinical_email', models.CharField(blank=True, help_text='Clinical Email', max_length=100)),
                ('notes', models.CharField(blank=True, help_text='Notes - Server Pre-Check', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SiteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag_info', models.ManyToManyField(help_text='Asset Tag Information', to='core.AssetTagModel')),
            ],
        ),
        migrations.AddField(
            model_name='assettagmodel',
            name='case_number_info',
            field=models.ManyToManyField(help_text='Case Number Information', to='core.CaseNumberModel'),
        ),
    ]
