# Generated by Django 2.2.2 on 2019-07-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casenumbermodel',
            old_name='clinical_email',
            new_name='Clinical_Email',
        ),
        migrations.RenameField(
            model_name='casenumbermodel',
            old_name='contact_cust',
            new_name='Contacted_Customer',
        ),
        migrations.RenameField(
            model_name='casenumbermodel',
            old_name='dosecalc_suppression',
            new_name='DoseCalc_Suppression',
        ),
        migrations.RenameField(
            model_name='casenumbermodel',
            old_name='ip_page_updated',
            new_name='Followed_Up_With_Customer',
        ),
        migrations.RenameField(
            model_name='casenumbermodel',
            old_name='min_server_req',
            new_name='IP_Page_Updated',
        ),
        migrations.RenameField(
            model_name='casenumbermodel',
            old_name='minimum_rad_version',
            new_name='Minimum_Radimetrics_Requirements',
        ),
        migrations.RenameField(
            model_name='casenumbermodel',
            old_name='upa',
            new_name='Minimum_Server_Requirements',
        ),
        migrations.RenameField(
            model_name='casenumbermodel',
            old_name='primary_email',
            new_name='Primary_Email',
        ),
        migrations.RenameField(
            model_name='casenumbermodel',
            old_name='sdi_count',
            new_name='SDI_Count',
        ),
        migrations.RenameField(
            model_name='casenumbermodel',
            old_name='upgrade_complete',
            new_name='UPA',
        ),
        migrations.RenameField(
            model_name='casenumbermodel',
            old_name='upgrade_total_time',
            new_name='Upgrade_Total_Time',
        ),
        migrations.RemoveField(
            model_name='casenumbermodel',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='casenumbermodel',
            name='sched_upgrade_date',
        ),
        migrations.RemoveField(
            model_name='casenumbermodel',
            name='upgrade_date',
        ),
        migrations.RemoveField(
            model_name='casenumbermodel',
            name='wo_type',
        ),
        migrations.AddField(
            model_name='casenumbermodel',
            name='Followed_Up_With_Customer_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casenumbermodel',
            name='Notes',
            field=models.TextField(blank=True, help_text='Notes - Server Pre-Check', max_length=250),
        ),
        migrations.AddField(
            model_name='casenumbermodel',
            name='Scheduled_Upgrade_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casenumbermodel',
            name='Upgrade_Complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casenumbermodel',
            name='Upgrade_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casenumbermodel',
            name='Upgraded_By',
            field=models.CharField(choices=[('h', 'Heath Guy'), ('y', 'Yahia Hegazy')], default='-', max_length=1),
        ),
        migrations.AddField(
            model_name='casenumbermodel',
            name='WO_Type',
            field=models.CharField(blank=True, choices=[('s', 'VSS'), ('u', 'VCU')], default='-', help_text='Work Order Type', max_length=1),
        ),
    ]
