# Generated by Django 2.2.2 on 2019-07-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190714_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assettagmodel',
            name='case_number_info',
        ),
        migrations.AddField(
            model_name='assettagmodel',
            name='Case_Number_Details',
            field=models.ManyToManyField(help_text='Case Number Details', to='core.CaseNumberModel'),
        ),
    ]
