# Generated by Django 2.2.2 on 2019-07-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190714_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettagmodel',
            name='current_os_version',
            field=models.CharField(blank=True, choices=[('-', 'Pick One'), ('RedHat', 'RHEL'), ('OpenSuse', 'OpenSuse'), ('CentOS', 'CentOS')], default='-', help_text='Current OS Version', max_length=1),
        ),
    ]
