# Generated by Django 2.2.2 on 2019-07-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190714_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettagmodel',
            name='type_of_server',
            field=models.CharField(choices=[('-', 'Pick One'), ('Prod', 'PROD'), ('Test', 'TEST'), ('Contrast', 'CONTRAST ONLY'), ('Pre-Processor', 'PRE-PROCESSOR'), ('Enterprise', 'ENTERPRISE')], default='-', help_text='Type of Server', max_length=1),
        ),
        migrations.AlterField(
            model_name='casenumbermodel',
            name='Upgraded_By',
            field=models.CharField(choices=[('Heath', 'Heath Guy'), ('Yahia', 'Yahia Hegazy')], default='-', max_length=1),
        ),
        migrations.AlterField(
            model_name='casenumbermodel',
            name='WO_Type',
            field=models.CharField(blank=True, choices=[('VSS', 'VSS'), ('VCU', 'VCU')], default='-', help_text='Work Order Type', max_length=1),
        ),
    ]
