# Generated by Django 2.2.2 on 2019-07-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190714_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='name',
            field=models.CharField(blank=True, help_text='Hospital Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='assettagmodel',
            name='current_os_version',
            field=models.CharField(blank=True, choices=[('-', 'Pick One'), ('RedHat', 'RHEL'), ('OpenSuse', 'OpenSuse'), ('CentOS', 'CentOS')], default='-', help_text='Current OS Version', max_length=10),
        ),
        migrations.AlterField(
            model_name='assettagmodel',
            name='type_of_server',
            field=models.CharField(choices=[('-', 'Pick One'), ('Prod', 'PROD'), ('Test', 'TEST'), ('Contrast', 'CONTRAST ONLY'), ('Pre-Processor', 'PRE-PROCESSOR'), ('Enterprise', 'ENTERPRISE')], default='-', help_text='Type of Server', max_length=20),
        ),
        migrations.AlterField(
            model_name='casenumbermodel',
            name='Upgraded_By',
            field=models.CharField(choices=[('Heath', 'Heath Guy'), ('Yahia', 'Yahia Hegazy')], default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='casenumbermodel',
            name='WO_Type',
            field=models.CharField(blank=True, choices=[('VSS', 'VSS'), ('VCU', 'VCU')], default='-', help_text='Work Order Type', max_length=3),
        ),
    ]
