# Generated by Django 2.2.2 on 2019-07-14 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190714_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assettagmodel',
            name='Case_Number_Details',
        ),
        migrations.AddField(
            model_name='assettagmodel',
            name='Case_Number_Details',
            field=models.ForeignKey(help_text='Case Number Details', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CaseNumberModel'),
        ),
    ]
