# Generated by Django 2.2.2 on 2019-07-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190714_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assettagmodel',
            old_name='current_os_version',
            new_name='Current_OS_Version',
        ),
        migrations.RenameField(
            model_name='assettagmodel',
            old_name='current_rad_version',
            new_name='Current_Radimetrics_Version',
        ),
        migrations.RenameField(
            model_name='assettagmodel',
            old_name='type_of_server',
            new_name='Type_Of_Server',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='asset_tag_info',
            new_name='Asset_Tag_Information',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='name',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='assettagmodel',
            name='Asset_Number',
            field=models.CharField(default='', help_text='ie: 50001201161', max_length=50),
        ),
    ]
