# Generated by Django 2.2.2 on 2019-07-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190714_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='casenumbermodel',
            name='Case_Number',
            field=models.CharField(blank=True, help_text='ie: 0067824', max_length=100),
        ),
    ]
