# Generated by Django 2.2.2 on 2019-07-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_casenumbermodel_case_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetTagModel',
            new_name='Asset_Tags',
        ),
        migrations.RenameModel(
            old_name='SiteModel',
            new_name='Hospital_Sites',
        ),
        migrations.RenameModel(
            old_name='CaseNumberModel',
            new_name='Service_Max_Cases',
        ),
    ]

    atomic = False
