# Generated by Django 2.2.2 on 2019-07-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('core', '0010_auto_20190714_1455'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asset_Tags',
            new_name='AssetTag',
        ),
        migrations.RenameModel(
            old_name='Hospital_Sites',
            new_name='HospitalSite',
        ),
        migrations.RenameModel(
            old_name='Service_Max_Cases',
            new_name='ServiceMaxCase',
        ),
    ]
