# Generated by Django 2.2.2 on 2019-07-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190714_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettag',
            name='Current_CPU',
            field=models.CharField(default='', help_text='ie: 4', max_length=1),
        ),
        migrations.AddField(
            model_name='assettag',
            name='Current_Disks',
            field=models.CharField(default='', help_text='ie: 100/100/200', max_length=50),
        ),
        migrations.AddField(
            model_name='assettag',
            name='Current_RAM',
            field=models.CharField(default='', help_text='ie: 16', max_length=5),
        ),
    ]
