# Generated by Django 2.2.2 on 2019-07-16 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asset_Number', models.CharField(default='', help_text='ie: 50001201161', max_length=50)),
                ('Current_OS_Version', models.CharField(blank=True, choices=[('-', 'Pick One'), ('RedHat', 'RHEL'), ('OpenSuse', 'OpenSuse'), ('CentOS', 'CentOS')], default='-', help_text='Current OS Version', max_length=10)),
                ('Current_Radimetrics_Version', models.CharField(default='2.9.1b', help_text='Current Radimetrics Version ', max_length=10)),
                ('Type_Of_Server', models.CharField(choices=[('-', 'Pick One'), ('Prod', 'PROD'), ('Test', 'TEST'), ('Contrast', 'CONTRAST ONLY'), ('Pre-Processor', 'PRE-PROCESSOR'), ('Enterprise', 'ENTERPRISE')], default='-', help_text='Type of Server', max_length=20)),
                ('Current_Disks', models.CharField(default='', help_text='ie: 100/100/200', max_length=50)),
                ('Current_CPU', models.CharField(default='', help_text='ie: 4', max_length=5)),
                ('Current_RAM', models.CharField(default='', help_text='ie: 16', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMaxCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Case_Number', models.CharField(blank=True, help_text='ie: 0067824', max_length=100)),
                ('WO_Type', models.CharField(blank=True, choices=[('VSS', 'VSS'), ('VCU', 'VCU')], default='-', help_text='Work Order Type', max_length=3)),
                ('UPA', models.BooleanField()),
                ('Minimum_Server_Requirements', models.BooleanField()),
                ('Primary_Email', models.CharField(blank=True, help_text='Primary Email', max_length=100)),
                ('Clinical_Email', models.CharField(blank=True, help_text='Clinical Email', max_length=100)),
                ('Scheduled_Upgrade_Date', models.DateField(blank=True, null=True)),
                ('Contacted_Customer', models.BooleanField()),
                ('Followed_Up_With_Customer', models.BooleanField()),
                ('Followed_Up_With_Customer_Date', models.DateField(blank=True, null=True)),
                ('Upgrade_Complete', models.BooleanField(default=False)),
                ('Upgrade_Date', models.DateField(blank=True, null=True)),
                ('Upgrade_Total_Time', models.IntegerField(default=0)),
                ('Upgraded_By', models.CharField(choices=[('-', 'Pick One'), ('Heath', 'Heath Guy'), ('Yahia', 'Yahia Hegazy')], default='-', max_length=10)),
                ('DoseCalc_Suppression', models.BooleanField()),
                ('IP_Page_Updated', models.BooleanField()),
                ('SDI_Count', models.IntegerField(default=0)),
                ('Notes', models.TextField(blank=True, help_text='Notes - Server Pre-Check', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, help_text='Hospital Name', max_length=100)),
                ('Asset_Tag_Information', models.ManyToManyField(help_text='Asset Tag Information', to='demo.AssetTag')),
            ],
        ),
        migrations.AddField(
            model_name='assettag',
            name='Case_Number_Details',
            field=models.ForeignKey(help_text='Case Number Details', null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.ServiceMaxCase'),
        ),
    ]
