# Generated by Django 2.2.2 on 2020-02-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_Name', models.CharField(blank=True, help_text='Hospital Name', max_length=100)),
                ('Serial_Number', models.CharField(default='', help_text='ie: 50001201161', max_length=50)),
                ('Current_OS_Version', models.CharField(blank=True, choices=[('-', 'Pick One'), ('RedHat', 'RedHat'), ('OpenSuse', 'OpenSuse'), ('CentOS', 'CentOS')], default='-', help_text='Current OS Version', max_length=10)),
                ('Current_Radimetrics_Version', models.CharField(default='2.9.1b', help_text='ie: 2.9.1b ', max_length=10)),
                ('Type_Of_Server', models.CharField(choices=[('-', 'Pick One'), ('PROD', 'PROD'), ('TEST', 'TEST'), ('CONTRAST', 'CONTRAST ONLY'), ('PREPROCESSOR', 'PRE-PROCESSOR'), ('ENTERPRISE', 'ENTERPRISE'), ('APP', 'APP'), ('DB', 'DB')], default='-', help_text='Server Type', max_length=20)),
                ('Disk_1', models.CharField(default='100', max_length=50)),
                ('Disk_2', models.CharField(default='100', max_length=50)),
                ('Disk_3', models.CharField(default='200', max_length=50)),
                ('Current_CPU', models.CharField(default='', help_text='ie: 4', max_length=5)),
                ('Current_RAM', models.CharField(default='', help_text='ie: 16', max_length=5)),
                ('DB_Version', models.CharField(blank=True, default='', help_text='ie: 8.4', max_length=10)),
                ('DB_Size1', models.CharField(blank=True, default='50', help_text='ie: 100GB', max_length=50)),
                ('DB_Size2', models.CharField(blank=True, default='', help_text='ie: 5', max_length=50)),
                ('Site_Hostname', models.CharField(blank=True, default='', help_text='ie: hostname.domain.local', max_length=100)),
                ('Site_IP_Address', models.CharField(blank=True, default='', help_text='ie: 127.0.0.1', max_length=100)),
                ('Notes', models.TextField(blank=True, default='', max_length=1250)),
                ('Decommission', models.BooleanField(default=False)),
                ('Serial_Removed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['Site_Name'],
            },
        ),
    ]
