# Generated by Django 2.2.2 on 2020-02-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='DB_Size2',
            field=models.CharField(blank=True, default=False, help_text='ie: 5', max_length=50),
        ),
    ]
