# Generated by Django 2.2.2 on 2019-12-27 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteinformation',
            options={'ordering': ['Hospital_Name']},
        ),
    ]
