# Generated by Django 2.2.2 on 2020-01-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='Decommission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='Remove_from_Axeda',
            field=models.BooleanField(default=False),
        ),
    ]
