# Generated by Django 2.2.2 on 2020-01-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20200111_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinformation',
            old_name='Remove_from_Axeda',
            new_name='Serial_Removed',
        ),
    ]
