# Generated by Django 2.2.2 on 2020-01-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20191227_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='DB_Version',
            field=models.CharField(blank=True, default='', help_text='ie: 8.4', max_length=5),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='ExposureDB_Size',
            field=models.CharField(blank=True, default='', help_text='ie: 600', max_length=50),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='MirthDB_Size',
            field=models.CharField(blank=True, default='', help_text='ie: 5', max_length=50),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='Notes',
            field=models.TextField(blank=True, default='', help_text='ie: 600', max_length=1250),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='Site_Hostname',
            field=models.CharField(blank=True, default='', help_text='ie: eXposure.domain.local', max_length=100),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='Site_IP_Address',
            field=models.CharField(blank=True, default='', help_text='ie: 127.0.0.1', max_length=100),
        ),
    ]
