# Generated by Django 2.2.2 on 2020-02-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20200207_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinformation',
            old_name='Current_Radimetrics_Version',
            new_name='Current_Software_Version',
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='DB_Size2',
            field=models.CharField(blank=True, default='', help_text='ie: 5', max_length=50),
        ),
    ]
