# Generated by Django 2.2.2 on 2020-01-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20200112_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteinformation',
            options={'ordering': ['Site_Name']},
        ),
        migrations.RenameField(
            model_name='siteinformation',
            old_name='Hospital_Name',
            new_name='Site_Name',
        ),
    ]
