# Generated by Django 2.2.2 on 2020-02-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20200207_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='DB_Size2',
            field=models.CharField(blank=True, default='25', help_text='ie: 5', max_length=50),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='Site_Name',
            field=models.CharField(blank=True, help_text='Site Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='Type_Of_Server',
            field=models.CharField(choices=[('-', 'Pick One'), ('PROD', 'PROD'), ('TEST', 'TEST'), ('APP', 'APP'), ('DB', 'DB')], default='-', help_text='Server Type', max_length=20),
        ),
    ]
