# Generated by Django 2.2.2 on 2020-01-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20200101_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='DB_Unit',
            field=models.CharField(choices=[('-', 'Pick One'), ('GB', 'GB'), ('MB', 'MB'), ('KB', 'KB')], default='-', max_length=2),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='Notes',
            field=models.TextField(blank=True, default='', max_length=1250),
        ),
    ]
