# Generated by Django 2.2.2 on 2020-01-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20200101_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='Notes',
            field=models.TextField(blank=True, default='', max_length=1250),
        ),
    ]
