# Generated by Django 2.2.2 on 2020-01-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20200103_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='Current_OS_Version',
            field=models.CharField(blank=True, choices=[('-', 'Pick One'), ('RedHat', 'RedHat'), ('OpenSuse', 'OpenSuse'), ('CentOS', 'CentOS')], default='-', help_text='Current OS Version', max_length=10),
        ),
    ]
