# Generated by Django 2.2.2 on 2020-02-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20200215_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='Type_Of_Server',
            field=models.CharField(choices=[('-', 'Pick One'), ('PROD', 'Production'), ('TEST', 'Test'), ('APP', 'Application'), ('DB', 'Database')], default='-', help_text='Server Type', max_length=20),
        ),
    ]
