# Generated by Django 2.2.2 on 2020-01-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20200112_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinformation',
            old_name='Asset_Number',
            new_name='Serial_Number',
        ),
    ]
