# Generated by Django 2.2.2 on 2020-01-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20200101_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinformation',
            name='DB_Unit',
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='Current_RAM',
            field=models.CharField(default='', help_text='ie: 16GB', max_length=5),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='ExposureDB_Size',
            field=models.CharField(blank=True, default='', help_text='ie: 26GB, 600MB, 1000KB', max_length=50),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='MirthDB_Size',
            field=models.CharField(blank=True, default='', help_text='ie: 5GB, 857MB', max_length=50),
        ),
    ]
