# Generated by Django 2.2.2 on 2020-01-01 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20200101_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinformation',
            name='Account_Name',
            field=models.CharField(blank=True, help_text='Site Account Name', max_length=250),
        ),
        migrations.AddField(
            model_name='accountinformation',
            name='Site_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.SiteInformation'),
        ),
    ]
